version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
      - npm run install:lambda
  build:
    commands:
      - npm run deploy:cicd
  post_build:
    commands:
      - npm run test:remote
